# Generated by Django 3.2.2 on 2021-06-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='description',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='image',
            field=models.ImageField(default='', upload_to='contistituency_image/'),
        ),
    ]
