<<<<<<< HEAD
# Generated by Django 3.2.2 on 2021-06-14 09:34
=======
# Generated by Django 3.2.2 on 2021-06-14 09:30
>>>>>>> b86a7875c774523093711147cd611c1c509f7e77

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210613_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
