# Generated by Django 3.2.2 on 2021-06-16 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assembly_man_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ass', to='users.constituency'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='med_center_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='med', to='users.constituency'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec', to='users.constituency'),
        ),
    ]
