# Generated by Django 3.2.2 on 2021-10-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_restuuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
