<<<<<<< HEAD
# Generated by Django 3.2.2 on 2021-06-13 17:29
=======
# Generated by Django 3.2.2 on 2021-06-14 09:30
>>>>>>> b86a7875c774523093711147cd611c1c509f7e77

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
