# Generated by Django 3.2.2 on 2021-10-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituent_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
