# Generated by Django 3.2.2 on 2021-06-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaloperationsswitch',
            name='open_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generaloperationsswitch',
            name='open_forum',
            field=models.BooleanField(default=False),
        ),
    ]
