# Generated by Django 3.2.2 on 2021-11-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_operations', '0002_auto_20210611_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaloperationsswitch',
            name='show_notice',
            field=models.BooleanField(default=False),
        ),
    ]
