# Generated by Django 3.2.2 on 2021-11-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin_operations', '0003_generaloperationsswitch_show_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaloperationsswitch',
            old_name='show_notice',
            new_name='acshow_notice',
        ),
    ]
