# Generated by Django 3.2.2 on 2021-06-12 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=40000)),
                ('date_sent', models.DateTimeField(auto_now_add=True, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.constituency')),
                ('current_mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
